### GET Movies
GET http://localhost:8080/movies?year=2022 HTTP/1.1

### empty year
GET http://localhost:8080/movies?year= HTTP/1.1

### no year
GET http://localhost:8080/movies HTTP/1.1

### get by id
GET http://localhost:8080/movies/1 HTTP/1.1

### GET with Errors
GET http://localhost:8080/error HTTP/1.1